# Site settings
title: Code Thoughts
email: 96dalex@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just my thoughts about the codes and related topics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dalexj.github.io/" # the base hostname & protocol for your site
twitter_username: minishguy
github_username:  dalexj

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  use_coderay: true
  coderay:
    coderay_line_numbers: table
    coderay_css: class
